import { db } from '@/lib/db'
import { kbliChecks, negativeNtbChecks } from '@/lib/db/schema'
import { eq } from 'drizzle-orm'
import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

const fallbackCrossTable = [
  {
    assignmentId: 'TBN-00124',
    namaPrincipal: 'Warung Sumber Rejeki',
    ntbKbliAkhir: '47111',
    ntbKategori: 'Perdagangan',
    ntbCatatan: 'Omzet belum terisi lengkap',
    ntbNilaiTambah: '0',
    ntbLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00124',
    ntbId: 101,
    ntbLevel2FullCode: '52',
    ntbLevel6FullCode: '5260101001',
    ntbTahunOperasi: 2024,
    ntbOmzet: '0',
    ntbBiayaPembelian: '0',
    ntbBiayaProduksi: '0',
    ntbBiayaOperasional: '0',
    ntbSourceFile: 'ntb_2025.csv',
    ntbSourceFolder: 'Tuban/01',

    kbliId: 1,
    kbliAssignmentId: 'TBN-00124',
    kbliNamaUsaha: 'Warung Sumber Rejeki',
    kbliAkhir: '47111',
    kbliNamaPrelist: 'Warung Sumber Rejeki',
    kbliKategori: 'Perdagangan',
    kbliStatus: 'Selesai Dicek',
    kbliKegUtama: 'Jual sembako dan kebutuhan harian',
    kbliLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00124',
    kbliLevel3FullCode: 'G.47',
    kbliLevel3Name: 'Perdagangan Eceran',
    kbliLevel4FullCode: '471',
    kbliLevel4Name: 'Perdagangan Eceran di Toko',
    kbliLevel6FullCode: '47111',
    kbliLevel6Name: 'Perdagangan Eceran Berbagai Barang yang Utamanya Makanan di Toko',
    kbliAssignmentStatusAlias: 'Aktif',
    kbliKategori2025: 'Perdagangan',
    kbliIndex1: 'Negatif',
  },
  {
    assignmentId: 'TBN-00125',
    namaPrincipal: 'Bengkel Maju Jaya',
    ntbKbliAkhir: '45201',
    ntbKategori: 'Jasa',
    ntbCatatan: 'Perlu konfirmasi biaya pembelian spare part',
    ntbNilaiTambah: '3.600.000',
    ntbLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00125',
    ntbId: 102,
    ntbLevel2FullCode: '52',
    ntbLevel6FullCode: '5260101002',
    ntbTahunOperasi: 2023,
    ntbOmzet: '12.000.000',
    ntbBiayaPembelian: '4.500.000',
    ntbBiayaProduksi: '1.800.000',
    ntbBiayaOperasional: '2.100.000',
    ntbSourceFile: 'ntb_2025.csv',
    ntbSourceFolder: 'Tuban/01',

    kbliId: 2,
    kbliAssignmentId: 'TBN-00125',
    kbliNamaUsaha: 'Bengkel Maju Jaya',
    kbliAkhir: '45201',
    kbliNamaPrelist: 'Bengkel Maju Jaya',
    kbliKategori: 'Jasa',
    kbliStatus: 'Perlu Konfirmasi',
    kbliKegUtama: 'Bengkel perbaikan mesin & ganti oli kendaraan',
    kbliLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00125',
    kbliLevel3FullCode: 'S.95',
    kbliLevel3Name: 'Reparasi Komputer & Barang Keperluan Pribadi',
    kbliLevel4FullCode: '452',
    kbliLevel4Name: 'Reparasi dan Perawatan Mobil',
    kbliLevel6FullCode: '45201',
    kbliLevel6Name: 'Reparasi Mobil dan Mesin Kendaraan Bermotor',
    kbliAssignmentStatusAlias: 'Aktif',
    kbliKategori2025: 'Jasa Reparasi',
    kbliIndex1: 'Positif',
  },
  {
    assignmentId: 'TBN-00126',
    namaPrincipal: 'Toko Berkah',
    ntbKbliAkhir: '47112',
    ntbKategori: 'Perdagangan',
    ntbCatatan: 'Data lengkap dan valid sesuai kuisioner',
    ntbNilaiTambah: '4.400.000',
    ntbLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00126',
    ntbId: 103,
    ntbLevel2FullCode: '52',
    ntbLevel6FullCode: '5260101003',
    ntbTahunOperasi: 2024,
    ntbOmzet: '8.600.000',
    ntbBiayaPembelian: '2.100.000',
    ntbBiayaProduksi: '900.000',
    ntbBiayaOperasional: '1.100.000',
    ntbSourceFile: 'ntb_2025.csv',
    ntbSourceFolder: 'Tuban/02',

    kbliId: 3,
    kbliAssignmentId: 'TBN-00126',
    kbliNamaUsaha: 'Toko Berkah',
    kbliAkhir: '47112',
    kbliNamaPrelist: 'Toko Berkah',
    kbliKategori: 'Perdagangan',
    kbliStatus: 'Belum Dicek',
    kbliKegUtama: 'Penjualan eceran sembako dan kelontong',
    kbliLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00126',
    kbliLevel3FullCode: 'G.47',
    kbliLevel3Name: 'Perdagangan Eceran',
    kbliLevel4FullCode: '471',
    kbliLevel4Name: 'Perdagangan Eceran',
    kbliLevel6FullCode: '47112',
    kbliLevel6Name: 'Minimarket dan Toko Kelontong',
    kbliAssignmentStatusAlias: 'Aktif',
    kbliKategori2025: 'Perdagangan',
    kbliIndex1: 'Positif',
  },
  {
    assignmentId: 'TBN-00127',
    namaPrincipal: 'Roti Bu Tini',
    ntbKbliAkhir: '10710',
    ntbKategori: 'Industri',
    ntbCatatan: 'NTB normal di atas rata-rata klaster',
    ntbNilaiTambah: '7.500.000',
    ntbLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00127',
    ntbId: 104,
    ntbLevel2FullCode: '52',
    ntbLevel6FullCode: '5260101004',
    ntbTahunOperasi: 2022,
    ntbOmzet: '24.500.000',
    ntbBiayaPembelian: '11.000.000',
    ntbBiayaProduksi: '3.200.000',
    ntbBiayaOperasional: '2.800.000',
    ntbSourceFile: 'ntb_2025.csv',
    ntbSourceFolder: 'Tuban/02',

    kbliId: 4,
    kbliAssignmentId: 'TBN-00127',
    kbliNamaUsaha: 'Roti Bu Tini',
    kbliAkhir: '10710',
    kbliNamaPrelist: 'Roti Bu Tini',
    kbliKategori: 'Industri',
    kbliStatus: 'Selesai Dicek',
    kbliKegUtama: 'Produksi roti manis dan aneka kue basah',
    kbliLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00127',
    kbliLevel3FullCode: 'C.10',
    kbliLevel3Name: 'Industri Makanan',
    kbliLevel4FullCode: '107',
    kbliLevel4Name: 'Industri Makanan Lainnya',
    kbliLevel6FullCode: '10710',
    kbliLevel6Name: 'Industri Produk Roti dan Kue',
    kbliAssignmentStatusAlias: 'Aktif',
    kbliKategori2025: 'Industri Pengolahan',
    kbliIndex1: 'Positif',
  },
  {
    assignmentId: 'TBN-00128',
    namaPrincipal: 'RM Ikan Bakar Tuban',
    ntbKbliAkhir: '56101',
    ntbKategori: 'Akomodasi & Makan Minum',
    ntbCatatan: 'Biaya pembelian bahan baku melebihi estimasi omzet',
    ntbNilaiTambah: '-800.000',
    ntbLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00128',
    ntbId: 105,
    ntbLevel2FullCode: '52',
    ntbLevel6FullCode: '5260101005',
    ntbTahunOperasi: 2021,
    ntbOmzet: '18.000.000',
    ntbBiayaPembelian: '14.200.000',
    ntbBiayaProduksi: '2.100.000',
    ntbBiayaOperasional: '2.500.000',
    ntbSourceFile: 'ntb_2025.csv',
    ntbSourceFolder: 'Tuban/03',

    kbliId: 5,
    kbliAssignmentId: 'TBN-00128',
    kbliNamaUsaha: 'RM Ikan Bakar Tuban',
    kbliAkhir: '56101',
    kbliNamaPrelist: 'RM Ikan Bakar Tuban',
    kbliKategori: 'Akomodasi & Makan Minum',
    kbliStatus: 'Perlu Konfirmasi',
    kbliKegUtama: 'Warung makan ikan bakar dan sari laut',
    kbliLinkFasih: 'https://fasih.bps.go.id/survey/TBN-00128',
    kbliLevel3FullCode: 'I.56',
    kbliLevel3Name: 'Penyediaan Makanan dan Minuman',
    kbliLevel4FullCode: '561',
    kbliLevel4Name: 'Restoran dan Rumah Makan',
    kbliLevel6FullCode: '56101',
    kbliLevel6Name: 'Restoran/Rumah Makan Tradisional',
    kbliAssignmentStatusAlias: 'Aktif',
    kbliKategori2025: 'Penyediaan Makan Minum',
    kbliIndex1: 'Negatif',
  },
]

export async function GET() {
  try {
    const rows = await db
      .select({
        assignmentId: negativeNtbChecks.assignmentId,
        namaPrincipal: negativeNtbChecks.namaPrincipal,
        ntbKbliAkhir: negativeNtbChecks.kbliAkhir,
        ntbKategori: negativeNtbChecks.kategori,
        ntbCatatan: negativeNtbChecks.catatan,
        ntbNilaiTambah: negativeNtbChecks.nilaiTambah,
        ntbLinkFasih: negativeNtbChecks.linkFasih,
        ntbId: negativeNtbChecks.id,
        ntbLevel2FullCode: negativeNtbChecks.level2FullCode,
        ntbLevel6FullCode: negativeNtbChecks.level6FullCode,
        ntbTahunOperasi: negativeNtbChecks.tahunOperasi,
        ntbOmzet: negativeNtbChecks.r27aOmzet,
        ntbBiayaPembelian: negativeNtbChecks.r26cBiayaPembelian,
        ntbBiayaProduksi: negativeNtbChecks.r26bBiayaProduksi,
        ntbBiayaOperasional: negativeNtbChecks.r26dBiayaOperasional,
        ntbSourceFile: negativeNtbChecks.sourceFile,
        ntbSourceFolder: negativeNtbChecks.sourceFolder,

        kbliId: kbliChecks.id,
        kbliAssignmentId: kbliChecks.assignmentId,
        kbliNamaUsaha: kbliChecks.namaUsaha,
        kbliAkhir: kbliChecks.kbliAkhir,
        kbliNamaPrelist: kbliChecks.namaDiPrelist,
        kbliKategori: kbliChecks.kategori,
        kbliStatus: kbliChecks.status,
        kbliKegUtama: kbliChecks.kegUtama,
        kbliLinkFasih: kbliChecks.linkFasih,
        kbliLevel3FullCode: kbliChecks.level3FullCode,
        kbliLevel3Name: kbliChecks.level3Name,
        kbliLevel4FullCode: kbliChecks.level4FullCode,
        kbliLevel4Name: kbliChecks.level4Name,
        kbliLevel6FullCode: kbliChecks.level6FullCode,
        kbliLevel6Name: kbliChecks.level6Name,
        kbliAssignmentStatusAlias: kbliChecks.assignmentStatusAlias,
        kbliKategori2025: kbliChecks.kategori2025,
        kbliIndex1: kbliChecks.index1,
      })
      .from(negativeNtbChecks)
      .fullJoin(kbliChecks, eq(negativeNtbChecks.assignmentId, kbliChecks.assignmentId))
      .limit(1000)

    if (rows && rows.length > 0) {
      return NextResponse.json(rows)
    }
  } catch (error) {
    console.error('Error querying check-data cross-table:', error)
  }

  return NextResponse.json(fallbackCrossTable)
}
