-- ==============================================================================
-- DATABASE SEED: Initial Data for Monitoring Kualitas Data BPS Kabupaten Tuban
-- ==============================================================================

-- 1. Initial Users
INSERT INTO "user" (id, name, email, "emailVerified", username, role, bidang, "createdAt", "updatedAt")
VALUES 
    ('usr-admin-01', 'Admin BPS Tuban', 'admin@bps.tuban.go.id', true, 'admin', 'Administrator', 'Distribusi', NOW(), NOW()),
    ('usr-rina-02', 'Admin Rina', 'rina@bps.tuban.go.id', true, 'rina', 'Administrator', 'Produksi', NOW(), NOW()),
    ('usr-dwi-03', 'Dwi Santoso', 'dwi.santoso@bps.tuban.go.id', true, 'dwisantoso', 'Petugas Kualitas', 'Distribusi', NOW(), NOW()),
    ('usr-eko-04', 'Eko Hardi', 'eko.hardi@bps.tuban.go.id', true, 'ekohardi', 'Reviewer', 'Sosial', NOW(), NOW())
ON CONFLICT (id) DO UPDATE 
SET 
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    username = EXCLUDED.username,
    role = EXCLUDED.role,
    bidang = EXCLUDED.bidang;

-- Fallback user ID reference used in API routes
INSERT INTO "user" (id, name, email, "emailVerified", username, role, bidang, "createdAt", "updatedAt")
VALUES ('bps-admin-user', 'Admin BPS Tuban', 'admin.system@bps.tuban.go.id', true, 'bpsadmin', 'Administrator', 'Distribusi', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Initial User Credentials (Default password: admin123)
-- Hash generated by Better Auth scrypt algorithm
INSERT INTO "account" (id, "accountId", "providerId", "userId", password, "createdAt", "updatedAt")
VALUES 
    ('acc-admin-01', 'usr-admin-01', 'credential', 'usr-admin-01', '4dd92f9150f20ea014e5b128a3e55f51:7d34ff278bca18ee81c4bb2ed508cccf007510f5a75b7f56b45a92341fbdff5912386b1eae640eabe5e6e712aa7d13430c7c68e25e4e50bf03164fb2742234f7', NOW(), NOW()),
    ('acc-rina-02', 'usr-rina-02', 'credential', 'usr-rina-02', '4dd92f9150f20ea014e5b128a3e55f51:7d34ff278bca18ee81c4bb2ed508cccf007510f5a75b7f56b45a92341fbdff5912386b1eae640eabe5e6e712aa7d13430c7c68e25e4e50bf03164fb2742234f7', NOW(), NOW()),
    ('acc-dwi-03', 'usr-dwi-03', 'credential', 'usr-dwi-03', '4dd92f9150f20ea014e5b128a3e55f51:7d34ff278bca18ee81c4bb2ed508cccf007510f5a75b7f56b45a92341fbdff5912386b1eae640eabe5e6e712aa7d13430c7c68e25e4e50bf03164fb2742234f7', NOW(), NOW()),
    ('acc-eko-04', 'usr-eko-04', 'credential', 'usr-eko-04', '4dd92f9150f20ea014e5b128a3e55f51:7d34ff278bca18ee81c4bb2ed508cccf007510f5a75b7f56b45a92341fbdff5912386b1eae640eabe5e6e712aa7d13430c7c68e25e4e50bf03164fb2742234f7', NOW(), NOW()),
    ('acc-sys-05', 'bps-admin-user', 'credential', 'bps-admin-user', '4dd92f9150f20ea014e5b128a3e55f51:7d34ff278bca18ee81c4bb2ed508cccf007510f5a75b7f56b45a92341fbdff5912386b1eae640eabe5e6e712aa7d13430c7c68e25e4e50bf03164fb2742234f7', NOW(), NOW())
ON CONFLICT (id) DO UPDATE 
SET password = EXCLUDED.password, "accountId" = EXCLUDED."accountId", "userId" = EXCLUDED."userId";

-- 2. Initial Sample KBLI Checks
INSERT INTO kbli_checks (
    assignment_id, nama_usaha, nama_di_prelist, kbli_akhir, kategori, kategori_2025,
    keg_utama, status, assignment_status_alias, level_3_full_code, level_3_name,
    level_4_full_code, level_4_name, level_6_full_code, level_6_name, index1, link_fasih,
    keterangan, perbaikan_kbli, check_kbli, check_ntb, check_kewajaran, checked_by, checked_at
) VALUES 
(
    'TBN-00124', 'Warung Sumber Rejeki', 'Warung Sumber Rejeki', '47111', 'Perdagangan', 'Perdagangan Eceran',
    'Penjualan sembako, beras, minyak goreng, dan kebutuhan pokok harian', 'Selesai Dicek', 'Aktif',
    'G.47', 'Perdagangan Eceran', '471', 'Perdagangan Eceran di Toko', '47111', 'Perdagangan Eceran Berbagai Barang yang Utamanya Makanan di Toko',
    'Negatif', 'https://fasih.bps.go.id/survey/TBN-00124', 'Perlu konfirmasi omzet dan sinkronisasi data', '47111',
    true, false, false, 'Admin Rina', '30 Sep 2026, 09:42'
),
(
    'TBN-00125', 'Bengkel Maju Jaya', 'Bengkel Maju Jaya', '45201', 'Jasa', 'Jasa Reparasi',
    'Reparasi dan pemeliharaan sepeda motor roda dua serta ganti oli', 'Perlu Konfirmasi', 'Aktif',
    'S.95', 'Reparasi Komputer & Keperluan Pribadi', '452', 'Reparasi Kendaraan Bermotor', '45201', 'Reparasi Mesin dan Kendaraan Bermotor Roda Dua',
    'Positif', 'https://fasih.bps.go.id/survey/TBN-00125', 'KBLI sudah sesuai bengkel motor', '45201',
    true, true, false, 'Dwi Santoso', '30 Sep 2026, 10:15'
),
(
    'TBN-00126', 'Toko Berkah', 'Toko Berkah', '47112', 'Perdagangan', 'Perdagangan Eceran',
    'Minimarket kelontong dan penjualan barang konsumsi sehari-hari', 'Belum Dicek', 'Aktif',
    'G.47', 'Perdagangan Eceran', '471', 'Perdagangan Eceran', '47112', 'Minimarket dan Toko Kelontong Modern',
    'Positif', 'https://fasih.bps.go.id/survey/TBN-00126', 'Kelontong modern minimarket', '47112',
    false, false, false, '', ''
),
(
    'TBN-00127', 'Roti Bu Tini', 'Roti Bu Tini', '10710', 'Industri', 'Industri Pengolahan',
    'Produksi aneka roti manis, kue basah, dan jajanan pasar', 'Selesai Dicek', 'Aktif',
    'C.10', 'Industri Makanan', '107', 'Industri Makanan Lainnya', '10710', 'Industri Produk Roti dan Kue',
    'Positif', 'https://fasih.bps.go.id/survey/TBN-00127', 'Industri roti dan kue basah skala mikro', '10710',
    true, true, true, 'Eko Hardi', '01 Okt 2026, 14:20'
),
(
    'TBN-00128', 'RM Ikan Bakar Tuban', 'RM Ikan Bakar Tuban', '56101', 'Akomodasi & Makan Minum', 'Penyediaan Makan Minum',
    'Rumah makan tradisional olahan ikan laut dan aneka seafood', 'Perlu Konfirmasi', 'Aktif',
    'I.56', 'Penyediaan Makanan dan Minuman', '561', 'Restoran dan Rumah Makan', '56101', 'Restoran dan Rumah Makan Tradisional Pesisir',
    'Negatif', 'https://fasih.bps.go.id/survey/TBN-00128', 'Perlu verifikasi pengeluaran bahan baku', '56101',
    true, false, false, 'Dwi Santoso', '02 Okt 2026, 11:05'
),
(
    'TBN-00129', 'Batik Tulis Tenun Gedog', 'Batik Tulis Tenun Gedog', '13121', 'Industri', 'Industri Pengolahan',
    'Pembuatan kain tenun gedog dan batik tulis khas Tuban', 'Selesai Dicek', 'Aktif',
    'C.13', 'Industri Tekstil', '131', 'Industri Pemintalan & Pertenunan', '13121', 'Industri Pertenunan Kain dan Batik Tradisional',
    'Positif', 'https://fasih.bps.go.id/survey/TBN-00129', 'Pengrajin tenun gedog dan batik tulis', '13121',
    true, true, true, 'Admin Rina', '03 Okt 2026, 16:30'
);

-- 3. Initial Sample Negative NTB Checks
INSERT INTO negative_ntb_checks (
    assignment_id, nama_principal, kategori, kbli_akhir, tahun_operasi, catatan,
    r27a_omzet, r26c_biaya_pembelian, r26b_biaya_produksi, r26d_biaya_operasional,
    nilai_tambah, level_2_full_code, level_6_full_code, link_fasih, source_file, source_folder
) VALUES 
(
    'TBN-00124', 'Warung Sumber Rejeki', 'Perdagangan', '47111', 2024,
    'Omzet belum terisi lengkap di form Fasih, perlu konfirmasi ulang',
    '0', '0', '0', '0', '0', '52', '5260101001', 'https://fasih.bps.go.id/survey/TBN-00124', 'ntb_2025.csv', 'Tuban/01'
),
(
    'TBN-00125', 'Bengkel Maju Jaya', 'Jasa', '45201', 2023,
    'Perlu konfirmasi rincian biaya pembelian spare part roda dua',
    '12.000.000', '4.500.000', '1.800.000', '2.100.000', '3.600.000', '52', '5260101002', 'https://fasih.bps.go.id/survey/TBN-00125', 'ntb_2025.csv', 'Tuban/01'
),
(
    'TBN-00126', 'Toko Berkah', 'Perdagangan', '47112', 2024,
    'Data penjualan dan pengeluaran lengkap sesuai pembukuan',
    '8.600.000', '2.100.000', '900.000', '1.100.000', '4.400.000', '52', '5260101003', 'https://fasih.bps.go.id/survey/TBN-00126', 'ntb_2025.csv', 'Tuban/02'
),
(
    'TBN-00127', 'Roti Bu Tini', 'Industri', '10710', 2022,
    'NTB normal dan konsisten dengan kapasitas produksi harian',
    '24.500.000', '11.000.000', '3.200.000', '2.800.000', '7.500.000', '52', '5260101004', 'https://fasih.bps.go.id/survey/TBN-00127', 'ntb_2025.csv', 'Tuban/02'
),
(
    'TBN-00128', 'RM Ikan Bakar Tuban', 'Akomodasi & Makan Minum', '56101', 2021,
    'Biaya pembelian ikan dan bumbu laut melebihi estimasi omzet',
    '18.000.000', '14.200.000', '2.100.000', '2.500.000', '-800.000', '52', '5260101005', 'https://fasih.bps.go.id/survey/TBN-00128', 'ntb_2025.csv', 'Tuban/03'
),
(
    'TBN-00129', 'Batik Tulis Tenun Gedog', 'Industri', '13121', 2023,
    'Biaya pembelian benang dan pewarna alami sebanding dengan nilai tambah',
    '16.000.000', '5.800.000', '2.400.000', '1.600.000', '6.200.000', '52', '5260101006', 'https://fasih.bps.go.id/survey/TBN-00129', 'ntb_2025.csv', 'Tuban/03'
);

-- 4. Initial Assignment Checklist Status
INSERT INTO assignment_checks (assignment_id, check_kbli, check_ntb, check_kewajaran, checked_by, checked_at)
VALUES 
    ('TBN-00124', true, false, false, 'Admin Rina', '30 Sep 2026, 09:42'),
    ('TBN-00125', true, true, false, 'Dwi Santoso', '30 Sep 2026, 10:15'),
    ('TBN-00126', false, false, false, '', ''),
    ('TBN-00127', true, true, true, 'Eko Hardi', '01 Okt 2026, 14:20'),
    ('TBN-00128', true, false, false, 'Dwi Santoso', '02 Okt 2026, 11:05'),
    ('TBN-00129', true, true, true, 'Admin Rina', '03 Okt 2026, 16:30')
ON CONFLICT (assignment_id) DO UPDATE
SET 
    check_kbli = EXCLUDED.check_kbli,
    check_ntb = EXCLUDED.check_ntb,
    check_kewajaran = EXCLUDED.check_kewajaran,
    checked_by = EXCLUDED.checked_by,
    checked_at = EXCLUDED.checked_at;

-- 5. Initial Activity Logs
INSERT INTO activity_logs (user_initials, user_name, action_text, created_at)
VALUES 
    ('AR', 'Admin Rina', 'Verifikasi KBLI assignment TBN-00124 selesai', NOW() - INTERVAL '3 days'),
    ('DS', 'Dwi Santoso', 'Pemeriksaan NTB Bengkel Maju Jaya (TBN-00125)', NOW() - INTERVAL '2 days'),
    ('EH', 'Eko Hardi', 'Selesai pemeriksaan menyeluruh Roti Bu Tini (TBN-00127)', NOW() - INTERVAL '1 day'),
    ('AD', 'Admin BPS Tuban', 'Inisialisasi sistem database pemantauan kualitas data', NOW());
